apiVersion: v1
kind: Service

metadata:
  name: backend
  namespace: lgtm

spec:
  selector:
    app: backend

  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}