apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: lgtm-ingress
  namespace: lgtm

spec:
  ingressClassName: {{ .Values.ingress.className }}

  rules:
    - host: {{ .Values.ingress.frontend.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: {{ .Values.frontend.service.port }}

    - host: {{ .Values.ingress.ipfs.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ipfs
                port:
                  number: {{ .Values.ipfs.service.gateway.port }}