apiVersion: v1
kind: Service

metadata:
  name: ipfs
  namespace: lgtm

spec:
  selector:
    app: ipfs

  ports:
    - name: gateway
      port: {{ .Values.ipfs.service.gateway.port }}
      targetPort: {{ .Values.ipfs.service.gateway.port }}