apiVersion: v1
kind: Service

metadata:
  name: ipfs-external
  namespace: lgtm

spec:
  type: LoadBalancer
  selector:
    app: ipfs

  ports:
    - name: swarm-tcp
      port: {{ .Values.ipfs.service.swarm.port }}
      targetPort: {{ .Values.ipfs.service.swarm.port }}
      protocol: TCP

    - name: swarm-udp
      port: {{ .Values.ipfs.service.swarm.port }}
      targetPort: {{ .Values.ipfs.service.swarm.port }}
      protocol: UDP
      
    - name: api
      port: {{ .Values.ipfs.service.api.port }}
      targetPort: {{ .Values.ipfs.service.api.port }}