apiVersion: apps/v1
kind: Deployment

metadata:
  name: otel-collector
  namespace: lgtm

spec:
  replicas: {{ .Values.otelcollector.replicaCount }}
  selector:
    matchLabels:
      app: otel-collector

  template:
    metadata:
      labels:
        app: otel-collector

    spec:
      containers:
        - name: otel-collector
          image: "{{ .Values.otelcollector.image.repository }}:{{ .Values.otelcollector.image.tag }}"
          imagePullPolicy: {{ .Values.otelcollector.image.pullPolicy }}
          command: ["--config", "/etc/otel-collector-config.yaml"]
          volumeMounts:
            - name: otel-collector-config
              mountPath: /etc/otel-collector-config.yaml
              subPath: otel-collector-config.yaml
          ports:
            - name: grpc
              containerPort: {{ .Values.otelcollector.service.grpc.port }}
            - name: webui
              containerPort: {{ .Values.otelcollector.service.webui.port }}
            - name: prometheus
              containerPort: {{ .Values.otelcollector.service.prometheus.port }}