root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/server ./cmd/server"
bin = "./tmp/server"
include_ext = ["go"]
exclude_dir = ["tmp", "vendor"]

[color]
main = "yellow"
watcher = "cyan"
build = "green"
runner = "magenta"