FROM golang:1.26-alpine

WORKDIR /app

RUN go install github.com/air-verse/air@latest
# RUN go get github.com/tetratelabs/wazero@latest

COPY go.mod go.sum ./
RUN go mod download

EXPOSE 4242

CMD ["air"]