services:

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile.dev
    container_name: lgtm-backend
    working_dir: /app
    command: air
    volumes:
      - ../backend:/app
    ports:
      - "4242:4242"
    networks:
      - lgtm

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.dev
    container_name: lgtm-frontend
    working_dir: /app
    command: npm run dev -- --host 0.0.0.0
    volumes:
      - ../frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:4242
    depends_on:
      - backend
    networks:
      - lgtm

  kubo:
    build:
      context: ../kubo
      dockerfile: Dockerfile.dev
    container_name: lgtm-kubo
    working_dir: /files
    volumes:
      - ../kubo:/files
    ports:
      - "5001:5001"
      - "8080:8080"
    networks:
      - lgtm

  prometheus:
    image: prom/prometheus:main-distroless@sha256:0422496748612c360ad4f6c528a486f72c0e78e5fb430b0c5ffe7a9a2a51f21d
    container_name: lgtm-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - lgtm

networks:
  lgtm:
    driver: bridge