services:

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile.dev
    container_name: lgtm-backend
    working_dir: /app
    command: air
    volumes:
      - ../backend:/app
    ports:
      - "4242:4242"
    networks:
      - lgtm

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.dev
    container_name: lgtm-frontend
    working_dir: /app
    command: npm run dev -- --host 0.0.0.0
    volumes:
      - ../frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:4242
    depends_on:
      - backend
    networks:
      - lgtm

  kubo:
    build:
      context: ../kubo
      dockerfile: Dockerfile.dev
    container_name: lgtm-kubo
    working_dir: /files
    volumes:
      - ../kubo:/files
    ports:
      - "5001:5001"
      - "8080:8080"
    networks:
      - lgtm

####################################################################
##                        LGTM Stack                              ##
####################################################################

  prometheus:
    image: prom/prometheus:main-distroless@sha256:0422496748612c360ad4f6c528a486f72c0e78e5fb430b0c5ffe7a9a2a51f21d
    container_name: lgtm-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - lgtm

  grafana:
    image: grafana/grafana:nightly-slim@sha256:5909f8f4123b9ff3efcd701e23c0b5310b6ae0ea12fd3ee906f2bc91831e5363
    container_name: lgtm-grafana
    volumes:
    - ./observability/grafana/provisioning:/etc/grafana/provisioning
    - ./observability/grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    networks:
      - lgtm

networks:
  lgtm:
    driver: bridge