apiVersion: v1
kind: Service

metadata:
  name: prometheus
  namespace: lgtm

spec:
  selector:
    app: prometheus


  ports:
    - name: grpc
      port: {{ .Values.prometheus.service.grpc.port }}
      targetPort: grpc
    - name: webui
      port: {{ .Values.prometheus.service.webui.port }}
      targetPort: webui
    - name: prometheus
      port: {{ .Values.prometheus.service.prometheus.port }}
      targetPort: prometheus