ingress:
  enabled: true
  className: traefik

  frontend:
    host: lgtm.local
    http:
      paths:
      unsecure: yes
  
  ipfs:
    host: ipfs.lgtm.local
    http:
      paths:
      unsecure: yes

frontend:
  service:
    port: 80
  image:
    repository: lgtm_front
    tag: latest
    pullPolicy: Always

  replicaCount: 1

backend:
  service:
      port: 4242
  image:
    repository: lgtm_back
    tag: latest
    pullPolicy: Always

  replicaCount: 1

ipfs:
  service:
    gateway:
      port: 8080
    api:
      port: 5001
    swarm:
      port: 4001

  image:
    repository: ipfs/kubo
    tag: v0.42.0
    pullPolicy: Always

  replicaCount: 1