apiVersion: v1
kind: ConfigMap

metadata:
  name: grafana-provisioning
  namespace: lgtm

data:
  datasources.yaml: |
{{ .Files.Get "files/grafana/provisioning/datasources/datasources.yaml" | indent 4 }}
  dashboards.yaml: |
{{ .Files.Get "files/grafana/provisioning/dashboards/dashboards.yaml" | indent 4 }}