apiVersion: k3d.io/v1alpha5

kind: Simple

metadata:
  name: lgtm

servers: 1
agents: 2

ports:
  - port: 80:80               # Client — public
    nodeFilters:
      - loadbalancer

  - port: 3000:3000           # Grafana — public
    nodeFilters:
      - loadbalancer

  - port: 8080:8080           # IPFS Gateway — public
    nodeFilters:
      - loadbalancer
  - port: 4001:4001           # swarm — public
    nodeFilters:
      - loadbalancer
  - port: 4001:4001/udp       # swarm — public
    nodeFilters:
      - loadbalancer
  - port: 127.0.0.1:5001:5001 # WebUI — local loopback only
    nodeFilters:
      - loadbalancer

options:
  k3d:
    wait: true
    timeout: "60s"

  kubeconfig:
    updateDefaultKubeconfig: true # add new cluster to your default Kubeconfig; same as `--kubeconfig-update-default` (default: true)
    switchCurrentContext: true # also set current-context to the new cluster's context; same as `--kubeconfig-switch-context` (default: true)
