apiVersion: v1
kind: Service

metadata:
  name: tempo
  namespace: lgtm

spec:
  selector:
    app: tempo

  ports:
    - name: backend
      port: {{ .Values.tempo.service.backend }}
      targetPort: {{ .Values.tempo.service.backend }}
    - name: grpc
      port: {{ .Values.tempo.service.grpc }}
      targetPort: {{ .Values.tempo.service.grpc }}
    - name: http
      port: {{ .Values.tempo.service.http }}
      targetPort: {{ .Values.tempo.service.http }}