apiVersion: v1
kind: Service

metadata:
  name: tempo
  namespace: lgtm

spec:
  selector:
    app: tempo

  ports:
    - name: backend
      port: {{ .Values.tempo.service.backend.port }}
      targetPort: backend
    - name: grpc
      port: {{ .Values.tempo.service.grpc.port }}
      targetPort: grpc
    - name: http
      port: {{ .Values.tempo.service.http.port }}
      targetPort: http