apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lgtm
  namespace: argocd

  annotations:
    argocd-image-updater.argoproj.io/image-list: |
      backend=ghcr.io/mrlouf/lgtm_back
      frontend=ghcr.io/mrlouf/lgtm_front

    argocd-image-updater.argoproj.io/backend.update-strategy: newest-build
    argocd-image-updater.argoproj.io/backend.helm.image-name: backend.image.repository
    argocd-image-updater.argoproj.io/backend.helm.image-tag: backend.image.tag

    argocd-image-updater.argoproj.io/frontend.update-strategy: newest-build
    argocd-image-updater.argoproj.io/frontend.helm.image-name: frontend.image.repository
    argocd-image-updater.argoproj.io/frontend.helm.image-tag: frontend.image.tag

spec:
  project: default
  source:
    repoURL: https://github.com/mrlouf/ft_lgtm.git
    targetRevision: main

    path: helm/lgtm

    helm:
      valuesObject:
        frontend:
          image:
            repository: ghcr.io/mrlouf/lgtm_front
            tag: latest

        backend:
          image:
            repository: ghcr.io/mrlouf/lgtm_back
            tag: latest

  destination:
    server: https://kubernetes.default.svc
    namespace: lgtm

  syncPolicy:

    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true