apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lgtm
  namespace: argocd

spec:
  project: default
  source:
    repoURL: https://github.com/mrlouf/ft_lgtm.git
    targetRevision: main

    path: helm/lgtm

    helm:
      valuesObject:
        frontend:
          image:
            repository: ghcr.io/mrlouf/lgtm_front
            tag: sha-dc60f39

        backend:
          image:
            repository: ghcr.io/mrlouf/lgtm_back
            tag: sha-dc60f39

  destination:
    server: https://kubernetes.default.svc
    namespace: lgtm

  syncPolicy:

    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true