apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lgtm
  namespace: argocd

  annotations:
    argocd-image-updater.argoproj.io/image-list: |
      backend=ghcr.io/mrlouf/lgtm_back
      frontend=ghcr.io/mrlouf/lgtm_front

    argocd-image-updater.argoproj.io/backend.update-strategy: newest-build
    argocd-image-updater.argoproj.io/backend.helm.image-name: backend.image.repository
    argocd-image-updater.argoproj.io/backend.helm.image-tag: backend.image.tag

    argocd-image-updater.argoproj.io/frontend.update-strategy: newest-build
    argocd-image-updater.argoproj.io/frontend.helm.image-name: frontend.image.repository
    argocd-image-updater.argoproj.io/frontend.helm.image-tag: frontend.image.tag

spec:
  project: default
  source:
    repoURL: https://github.com/mrlouf/ft_lgtm.git
    targetRevision: refs/heads/staging

    path: helm/lgtm

    helm:
      valuesObject:
        frontend:
          image:
            repository: ghcr.io/mrlouf/lgtm_front
            tag: latest

        backend:
          image:
            repository: ghcr.io/mrlouf/lgtm_back
            tag: latest

        ipfs:
          image:
            repository: ipfs/kubo
            tag: v0.42.0
            digest: sha256:8907cb0cc1ad5798f6bb1bb1341a800990c268e021cedfa317e8aa1a33864214

        otel-collector:
          image:
            repository: otel/opentelemetry-collector
            tag: 0.158.0-nightly.3484eb0-amd64
            digest: sha256:8b2768e2187144d44fc6e86ee7b8e03041df4dfa2a9b476f1172783e1a785d3f

        prometheus:
          image:
            repository: prom/prometheus
            tag: main-distroless
            digest: sha256:0422496748612c360ad4f6c528a486f72c0e78e5fb430b0c5ffe7a9a2a51f21d

        tempo:
          image:
            repository: grafana/tempo
            tag: 2.7.2
            digest: sha256:4b0277a9b572a4b1fa43b01468e58911ec214dd69d033f2cd476596d14de9fe3

        grafana:
          image:
            repository: grafana/grafana
            tag: nightly-slim
            digest: sha256:5909f8f4123b9ff3efcd701e23c0b5310b6ae0ea12fd3ee906f2bc91831e5363

        loki:
          image:
            repository: grafana/loki
            tag: 3.7.4
            digest: sha256:87f0a067673756a3cede1bcbf0c74875f7df9b09fddb53e399d0c576f756cfcc

  destination:
    server: https://kubernetes.default.svc
    namespace: lgtm

  syncPolicy:

    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true