apiVersion: v1
kind: Service

metadata:
  name: loki
  namespace: lgtm

spec:
  selector:
    app: loki

  ports:
    - name: grpc
      port: {{ .Values loki.service.grpc.port }}
      targetPort: grpc
    - name: http
      port: {{ .Values loki.service.http.port }}
      targetPort: http